# Site Data
title: "Enjoyment Work"
tagline: " â€” a Digital Garden ðŸŒ±"
name: "Brennan Kenneth Brown"
author_bio:
  "Hey there! My name is Brennan, I'm a 24-year-old MÃ©tis web developer and content strategist from Winnipeg,
  Manitoba and currently reside in Calgary, Alberta. I've recently compeleted a Full Stack Developer Program
  at EvolveU, and I'm looking to help those that need web development work done, or searching for ideas and
  management for their next content project."
description: "A Digital Garden: Capturing my daily thoughts and progress, as well as curated ideas with unique synthesisâ€”a personal zettelkasten."
footer_description:
  'The phrase "digital garden" is a metaphor for thinking about writing and creating that focuses less on the
  resulting "showpiece" and more on the process, care, and craft it takes to get there. While not everybody
  has or works in a dirt garden, we all share a familiarity with the idea of what a garden is.'
notes_url: "https://enjoyment-work.netlify.app"
profile_pic: "https://brennanbrown.ca/img/avatar.jpg"
favicon: /assets/img/favicon.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://enjoyment-work.netlify.app/" # the base hostname & protocol for your site, e.g. https://example.com
theme_color: white
encoding: utf-8

# Links and Social Media
donate_link: https://ko-fi.com/brennanbrown
repository: https://github.com/brennanbrown/enjoyment-work
github: https://github.com/brennanbrown
twitter: https://twitter.com/brennankbrown
portfolio: https://brennanbrown.ca
email: mail@brennanbrown.ca

# Build Settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-minifier
  - jekyll-toc

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

JEKYLL_ENV: "production"

collections:
  notes:
    output: true
    permalink: /notes/:title
  journals:
    output: true
    permalink: /journals/:title
  pages:
    output: true
    permalink: /page/:name

disqus:
  shortname: journalbar

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
      category: "Post"
      toc: true
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: post
      content-type: journals
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      content-type: pages

jekyll-archives:
  enabled: []
  layout: default
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no-toc
  list_class: section-nav
  sublist_class: ""
  item_class: entry
  item_prefix: toc-
